<a href="https://colab.research.google.com/github/SauloSaturn/Data-Science-Docs-/blob/main/Introdu%C3%A7%C3%A3o_ao_Python_Num%C3%A9rico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color = lightblue>1.Introdução

## <font color = lightblue>1.1. Execução com o Python

Fazendo o uso da primeira função e consequentemente a execução do primeiro código, que tem por objetivo imprimir mensagens na tela chamado de *prompt*, essa função recebe o nome de *print*. Para o uso de tal função use **print( )** com uma mensagem fechada por aspas duplas ("mensagem") ou aspas simples ('mensagem') entre os parêntesis.

In [ ]:
print("hello world")

hello world


<font color = lightblue>  **Cerquilha**





O uso do símbolo # (cerquilha) é utilizado para fazer comentários, no entanto, as aspas triplas simples ('''mensagem''') também podem ser utilizadas para fazer o mesmo diretamente na tela de código, isto é, no prompt de comando.

In [ ]:
# Comentario
'''Comentário'''

'Comentário'

## <font color = lightblue>1.2.Interação com o Python
A função que interage  diretamente com o usuário é chamada de *input*. Para o uso de tal função use **input( )** com uma mensagem fechada por aspas duplas ("mensagem") ou aspas simples ('mensagem') seguida de dois pontos ( : ) entre os parêntesis da função.



In [ ]:
# Input simples.
# Vamos criar um inpunt simples.
input("Digite algo: ")

Digite algo: Meu nome é Saulo


'Meu nome é Saulo'

In [ ]:
# Faremos um print composto de várias mensagens (inputs) de uma só vez.
print("Olá! Meu nome é" , input("Qual é seu primeiro nome?: "), input("Qual é seu sobrenome?: "), "e tenho" , input("Qaual é sua idade?: "), "anos.")

Qual é seu primeiro nome?: Saulo
Qual é seu sobrenome?: Maruno
Qaual é sua idade?: 29
Olá! Meu nome é Saulo Maruno e tenho 29 anos.


In [ ]:
# Podemos fazer um print composto de várias mensagens (inputs) de uma só vez de outra forma.
# Cada input receberá um "nome", isso será necessário para fazer o print.
input_nome = input("Qual é seu primeiro nome?: ")
input_sobrenome = input("Qual é seu sobrenome?: ")
input_idade = input("Qaual é sua idade?: ")
# Poderia fazer um print por vez, no entanto, concatenando pode-se compactar.
print("Olá! Meu nome é "+ input_nome, input_sobrenome + " e tenho " + input_idade + " anos.")

Qual é seu primeiro nome?: Saulo
Qual é seu sobrenome?: Maruno
Qaual é sua idade?: 29
Olá! Meu nome é Saulo Maruno e tenho 29 anos.


**Observação**: É de conhecimento que utilizamos nomes seguidos de igualdades para cada um dos inputs serem armazenados e posteriormente concatenados, esses nomes tratam-se de variáveis e junto com a concatenação serão abordados mais adiante no tópico dedicado de variáveis.

# <font color = lightblue>2.Operadores
Operadores são de suma importância na construção lógica de um algoritmo robustamente estruturado.

## <font color = lightblue>2.1.Operadores Matemáticos

As operações matemáticas podem ser escritas diretamente no prompt.

In [ ]:
# Soma (+).
5 + 3

8

In [ ]:
# Subtração (-).
5 - 3

2

In [ ]:
# multiplicação (*).
5 * 3

15

In [ ]:
# Potenciação (**).
5 ** 3

125

In [ ]:
# Divisão (/).
5 / 3

1.6666666666666667

In [ ]:
# Divisão Inteira (//).
# Caso a divisão tenha como resultado um valor não exato, tal operação só toma como resultado a parte inteira*, dispondo do resto*.
5 // 2

2

In [ ]:
# Resto da divisão (%).
# Caso a divisão tenha como resultado um valor não exato, tal operação só toma como resultado o resto*, dispondo da parte inteira*.
5 % 2

1

Muitas vezes será necessária a importação de funções (funções do pacote Python) para se realizar uma tarefa. Para fazer o cálculo de raiz quadrada deve se importar uma função apropriada. No caso *import* *math >* **math.sqrt( )**. Outra forma usual é utilizar um artifício matemático, elevando o número desejado a $1/2$, assim obetendo sua raíz quadrada.

In [ ]:
# Raíz quadrada utilizando import (import math > math.sqrt( )).
import math
math.sqrt(16)

4.0

In [ ]:
# Raíz quadrada utilizando potência.
# Elevando o número a 1/2.
16 ** (1/2)

4.0

**Observação**: O assunto de importação de pacotes no Python terá uma discussão em um capítulo dedicado.

## <font color = lightblue>2.2. Operadores de Atribuição

Os operadores de atribuição são úteis para simplificar a notação aritimética, algébrica e verbalizada de um algoritmo.

In [ ]:
# Atribuiçāo Simples.
# x recebe y
x = y

In [ ]:
# Atribuição de adição.
# x = x + y
x += y

In [ ]:
# Atrbuição da subtração.
# x = x - y
x -= y

In [ ]:
# Atrbuição da multiplicação.
# x = x * y
x *= y

In [ ]:
# Atribuição da divisão.
# x = x / y
x /= y

In [ ]:
# Atribuição da divisão inteira.
# x = x // y
x //= y

In [ ]:
# Atribuição do resto da divisão inteira.
# x = x % y
x %= y

In [ ]:
# Atribuição da potência.
# x = x ** y
x **= y

## <font color = lightblue>2.3.Operadores de Comparação
Os operadores de comparação ou operadores relacionais tem por objetivo central validar ou não sentenças lógicas, e portanto, sempre quando necessário o uso de um comparativo será retornado um booleano (será tratado devidamente no próximo tópico, por hora, observe os "**True**" e "**False**" que aparecerão nos códigos abaixo).

In [ ]:
# Comparação (==) lógica (igual); comparando se a igualdade é consistente.
print(1 ==1)
print(1 == 2)

True
False


In [ ]:
# Diferênça (!=).
print(2 != 1)
print(2 != 2)

True
False


In [ ]:
# Maior que (>).
print(2 > 1)
print(1 > 2)

True
False


In [ ]:
# Menor que (<).
print(1 < 2)
print(2 < 1)

True
False


In [ ]:
# Maior ou igual (>=).
print(2 >= 1)
print(2 >= 2)
print(1 >= 2)

True
True
False


In [ ]:
# Menor ou igual (<=).
print(1 <= 2)
print(1 <= 1)
print(2 <= 1)

True
True
False


## <font color = lightblue>2.4.Boolean
Booleanos só admite caractéres duais, da forma "um" ou "outro" excludentes. A forma mais primitiva na linguagem de mais baixo nível só admite 0 ou 1, por exemplo. Booleanos assumem outros valores como "true" e "false" vistos nos códigos anteriormente, porém podem ser operadores lógicos (tratados no próximo tópico) que também recorrentemente são chamados de operadores booleanos.

In [ ]:
print(1==1)
type(1==1) # A função type( ) verifica o tipo de qualquer carctére expresso no prompt.

bool

## <font color = lightblue>2.5.Operadores Lógicos
Os operadores lógicos ou operadores booleanos tem como utilidade efetuar comparações de sentenças compostas. Onde os símbolos matemáticos $\cap$ (união), $\cup$ (intersecção) e $\neg$ (negação) são renomeados como **and**, **or** e **not** respectivamente. Há também **is** e **is not**, afim de substituir alguns operadores comparativos.

In [ ]:
# "And" sempre retorna "true" quando as comparações forem ambas verdadeiras.
print(1 < 2 and 2 > 1)
print(1 < 2 and 1 > 2)

True
False


In [ ]:
# "Or" sempre retorna "true" quando uma das comparações for verdadeira.
print(1 < 2 or 2 > 1)
print(1 < 2 or 1 > 2)
print(2 < 1 or 1 > 2)

True
True
False


In [ ]:
# "Not" sempre retorna o inverso lógico de "true" e "false".
n = 1 < 2 and 2 > 1
m = 1 < 2 and 1 > 2
print(not(n))
print(not(m))

False
True


In [ ]:
# "Is" pode substituir o operador comparativo " == ".
print(2 == 2)
print(2 is 2)

True
True


<>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-19-e4ffe551fbaa>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print(2 is 2)


In [ ]:
# "Is not" pode substituir o operador comparativo " := ".
print(2 != 1)
print(2 is not 1)

True
True
True


<>:3: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:4: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:3: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:4: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-23-5bf9ddf05d49>:3: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  print(2 is not 1)
<ipython-input-23-5bf9ddf05d49>:4: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print(3 is 3)


# <font color = lightblue>3.Variáveis

As variáveis assim como na matemática trata-se de valores arbitrários, os quais podem receber qualquer valor ou caractére.
Para declarar uma variável, basta escolher um nome (identificador) para nomea-la e usar um sinal de *igual* ( $=$ ). Vale dizer que ao longo do estudo até o presente momento elas foram usadas em praticamente tudo. Pela política de boas práticas em Python, variáveis e funções(serão tratadas mais adiante) seus identificadores sempre começam com letras e sendo elas minúsculas, e separadas por underscore( _ ) caso seja uma composição delas.




In [ ]:
# lê-se: var recebe 2
var = 2
print(var)

2


## <font color = lightblue>3.1.Tipos de Variáveis


Principais tipos de variáveis são:

*inteiros* ($\mathbb{Z}$).

*flutuantes* ($\mathbb{R}$).

*strings* (textos e demais caractéres).



In [ ]:
# varável inteira
var_int = 2
# varável flutuante
var_float = 2.1
# variável string
var_string = "abc"
print("inteiro", var_int, "flutuante", var_float, "string", var_string)

inteiro 2 flutuante 2.1 string abc


Embora os tipos elementares de variáveis sejam numéricas e textuais, pode-se estrapolar pra outros tipos de variáveis específicas para determinadas circunstâncias. São algumas delas:

In [ ]:
string = str("Hello World")
inteiro = int(1)
flutuante = float(1.1)
complexo = complex(1j)
lista = list(["1", 2 , "três"])
tupula = tuple(("1", 2 , "três"))
dicionário = dict({"1" : 1, "2" : 3, "três" : 3})
contjunto = set(("A", "B", "C"))
byte = bytes(1)
# Mais adiante veremos isso de forma mais abrangente em tipos de dados.

In [ ]:
# Para verificar o tipo de uma variável use o comando type( ).
print(type(1))
print(type([1,2,3]))
print(type("Hello"))

<class 'int'>
<class 'list'>
<class 'str'>


In [ ]:
lista_aninhada = [[1,2,3],[4,5,6,7],[8,9],[[10,11,12], [13, 14, 15]]]
lista_aninhada[3][1][0]


13

## <font color = lightblue>3.2.Declarações e Operacões de Variáveis

<font color = lightblue> Declaração Múltipla de Variáveis


Podemos declarar simultaneamete inúmeras variáveis, de tal modo que simplifique o código.

In [ ]:
# Declarando simultaneamente.
# Declarando (tipo 1):
um, dois, tres = 1, 2, 3
print(um, dois, tres)
# Declarando (tipo 2):
a = b = c = 20
print(a, b, c)

1 2 3
20 20 20


<font color = lightblue> Concatenação

É possível operar entre strings (**concatenação**). Para operar strings e números serão necessárias conversões.

In [ ]:
=# Concatenando variáveis.
var_1 = "Variá"
var_2 = "veis"
print(var_1 + var_2)

Variáveis


<font color = lightblue> Type Casting

Pode se fazer uma conversão de um valor/caractére de uma variável através de uma declaração do type de um dado desejado, e entre parêntesis, o valor/caractére que deseja converter.

In [ ]:
# Type Casting (Convertendo uma variável)
var_3 = int(2.5)
print(var_3)

2


Usando o Type Casting podemos operar diferente tipos de variáveis.

In [ ]:
# Convertendo int para str:
var_4 = var_1
var_5 = str(3)
# Operando:
print((var_4) + (var_5))
# Convertendo e operando float como str:
var_6 = int("2")
var_7 = 30
print((var_6) * (var_7))

Variá3
60


## <font color = lightblue>3.3.Tratamento de Variáveis

Muitas vezes é necessário dar uma polida nas variáveis antes de trabalhar com elas. Algums funções abaixo podem auxiliar para o devido tratamento de variáveis.



<font color = lightblue> Arredondadmento de valores float

Usa-se a *round* para arredondamentos, dessa maneira, a função **round( )** é útil quando existem variáveis do tipo *float* com muitas casas decimais.


In [ ]:
pi = 3.141595
print(pi)
# Na função usamos a variável que queremos efetuar o arredondamento e depois o parâmetro de quantos decimais.
round(pi, 2)

3.141595


3.14

## <font color = lightblue>3.4.Tratamento de Strings

Existem inumeras funções para lidar com as strings afim de manipula-las, são algumas delas:

**replace( )**.

**startswith( )**.

**endswith( )**.

**count( )**.

**capitalize( )**.

**isdigit( )**.

**isalnum( )**.

**upper( )**.

**lower( )**.

**find( )**.

**split( )**.

**strip( )**.

Cada uma dessas funções irão receber a devida explicação abaixo.


In [ ]:
# Armazenando a variável parâmetro.
string_1 = "hello human, the number pi is: 3,14"
print(string_1)

hello human, the number pi is: 3,14


In [ ]:
# A string indesejável será substituída por uma string desejável em outra vairável*.
string_2 = string_1.replace("human", "world")
print(string_2)

hello world, the number pi is: 3,14


In [ ]:
# Verificar se um string começa com um determinado caractére.
string_1.startswith("hello")

True

In [ ]:
# Verificar se um string finaliza com um determinado caractére.
string_1.endswith("3,14")

True

In [ ]:
# Verificar quantas vezes um determinado caractére se repete em uma string.
string_2.count("o")

2

In [ ]:
# Deixa em letra maiúscula a primeiro carctére da string.
string_1.capitalize()

'Hello human, the number pi is: 3,14'

In [ ]:
# Verifica se uma string é alfanumérica (só possui letras e números).
string_1.isalnum()

False

In [ ]:
# Deixa todos os elementos da string em maiúsculo.
string_1.upper()

'HELLO HUMAN, THE NUMBER PI IS: 3,14'

In [ ]:
# Deixo todos os elementos da string em minúsculo.
string_1.lower()

'hello human, the number pi is: 3,14'

In [ ]:
# Encontra um carctére pela sua posição numérica.
string_1.find("pi")

24

In [ ]:
# Remove espaços do início e do final de uma string.
string_1.strip()

'hello human, the number pi is: 3,14'

In [ ]:
# Transforma a string em uma lista.
string_1.split(',')

['hello human', ' the number pi is: 3', '14']

<font color = lightblue> Comprimento de uma variável

A função *len* lida com contagens. A função **len( )** conta a quantidade de elementos dentro de uma variável ou sentença.

In [ ]:
Lista_1 = [1, 2, 3, 4, 5]
Tupla_1 =  (1, 2, 3)
Dicionário_1 = {"a" : 2, "b" : "dois"}
String_3 = "Hello World"
print("lista =", len(Lista_1))
print("tupla =", len(Tupla_1))
print("dicionário =", len(Dicionário_1))
print("string =", len(String_3))

lista = 5
tupla = 3
dicionário = 2
string = 11


##<font color = lightblue>3.4.Exercícios

<font color = yellow>  Exercício 1:

Criando um *script* determine a área de um triângulo qualquer em metros quadrados sabendo sua base $b$ e sua altura $h$.

Nota* A equação da área é dada por:

$$A_t = \frac{b\cdot h}{2}$$

In [ ]:
base = float(input("Insira uma base metros quadrados: " ))
altura = float(input("Insira uma altura metros quadrados: "))
area_triangulo = str(base * altura / 2)
print("A área é dada por: " + area_triangulo + " metros quadrados")

Insira uma base metros quadrados: 5
Insira uma altura metros quadrados: 2
A área é dada por: 5.0 metros quadrados


<font color = yellow> Exercício 2:

Criando um *script*, determine a distância entre dois pontos quaisquer $P_1$ e $P_2$ definidos pelas coordenadas cartesianas $(x_1, y_1)$ e $(x_2, y_2)$ respectivamente.

Nota* A equação da distância entre dois pontos é dada por:

$$d = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$$



In [ ]:
import math
ponto_x1 = float(input("Insira a coordenada x1 para o ponto 1: "))
ponto_y1 = float(input("Insira a coordenada y1 para o ponto 1: "))
ponto_x2 = float(input("Insira a coordenada x2 para o ponto 2: "))
ponto_y2 = float(input("Insira a coordenada y2 para o ponto 2: "))
distancia = math.sqrt((ponto_x2 - ponto_x1) ** 2 + (ponto_y2 - ponto_y1) ** 2)
print("A distância entre o ponto P1 (" + str(ponto_x1) + ", " + str(ponto_y1) + ") e o ponto P2 (" + str(ponto_x2) + ", " + str(ponto_y2) + ") é: " + str(distancia) +". ")

Insira a coordenada x1 para o ponto 1: 3
Insira a coordenada y1 para o ponto 1: -1
Insira a coordenada x2 para o ponto 2: 3
Insira a coordenada y2 para o ponto 2: 0
A distância entre o ponto P1 (3.0, -1.0) e o ponto P2 (3.0, 0.0) é: 1.0. 


#<font color = lightblue>4.Condicionais If , Elif e Else

Condições lógicas de suma importância para a robustez estrutural de um algoritmo.


## <font color = lightblue>4.1.Condição If
A instrução *if* em Python é usada para testar uma condição e executar um bloco de código se a condição for verdadeira. A sintaxe da instrução *if* é a seguinte:
Se a condição for verdadeira, o bloco de código será executado. Se a condição for falsa, o bloco de código não será executado.

In [ ]:
# Condição se a pessoa for menor de idade ela poderá acessar um site.
idade = int(input("Digite sua idade: "))

if idade >= 18:
  print('Acesso válido')

Digite sua idade: 21
Acesso válido


## <font color = lightblue>4.2.Condição Elif
A instrução *elif* em Python é usada para testar uma condição adicional se a primeira condição for falsa. A sintaxe da instrução *elif* é a seguinte:
Se a primeira condição for verdadeira, o bloco de código 1 será executado. Se a primeira condição for falsa e a segunda condição for verdadeira, o bloco de código 2 será executado. Se ambas as condições forem falsas, nenhum bloco de código será executado.

In [ ]:
# Condição se a pessoa for menor de idade ela poderá acessar um site.
idade = int(input("Digite sua idade: "))

if idade >= 18:
  print('Acesso válido')
elif idade < 18 and idade >= 14:
  print('Acesso sob análise')

Digite sua idade: 17
Acesso sob análise


##<font color = lightblue>4.3.Condição Else
A instrução *else* em Python é usada para executar um bloco de código se todas as outras condições forem falsas. A sintaxe da instrução *else* é a seguinte:
Se a primeira condição for verdadeira, o bloco de código 1 será executado. Se a primeira condição for falsa e a segunda condição for verdadeira, o bloco de código 2 será executado. Se ambas as condições forem falsas, o bloco de código 3 será executado.

In [ ]:
# Condição se a pessoa for menor de idade ela poderá acessar um site.
idade = int(input("Digite sua idade: "))

if idade >= 18:
  print('Acesso válido')
elif idade < 18 and idade >= 14:
  print('Acesso sob análise')
else:
  print('Acesso negado')

Digite sua idade: 11
Acesso negado


##<font color = lightblue>4.3.Exerícios


<font color = yellow>  Exercícios

Triângulos são classificados em equiláteros, isósceles ou escalenos. Os triângulos equiláteros possuem os três lados iguais. Os isósceles possuem apenas dois lados iguais e os escalenos têm os três lados distintos. Crie um código que leia os lados (valores numéricos somente) de um triângulo qualquer e o classifique.

In [ ]:
print('Informes os 3 lados do triângulo:')
a = float(input('Lado 1: '))
b = float(input('Lado 2: '))
c = float(input('Lado 3: '))
if (a > b + c) or (b > a + c) or (c > a + b):
    print('Triângulo inválido')
else:
    if (a == b) and (b == c):
        print('Triângulo equilátero')
    elif (a == b) or (b == c) or (a == c):
        print('Triângulo isósceles')
    else:
        print('Triângulo escaleno')

Informes os 3 lados do triângulo:
Lado 1: 4
Lado 2: 4
Lado 3: 2
Triângulo isósceles



# <font color = lightblue>5.Listas, Tupulas e Dicionários

Listas, Tupulas e Dicionários são usadas para classificarem tipos de dados. Existem três tipos de coleção de dados, são eles:

Listas; atribuidas por colchetes [ ].

Tuplas; atribuidas por parêntesis ( ).

Dicionários; atribuidos por chaves { }.

Observação: qualquer tipo de valor (numéricos e  textuais) pode ser atribuído para os tipos de dados.

## <font color = lightblue>5.1.Listas
Listas são coleções de dados do  tipo primitivo (int, float, string), composto (uma lista sendo um elemento de outra lista) ou misto (uma variedade de tipo de elementos em uma única lista). É importante saber que cada elemento que compõe uma lista ocupa uma posição (*índice*), separados por uma vírgula, que varia de $0$ a $n$ sendo $n\in\mathbb{N}$.

In [ ]:
l1 = [1, 2, 3]
l2 = ["Hello", "World", "!"]
l3 = [l2, l1]
print(l1) # Lista composta por dados numéricos.
print(l2) # Lista composta por dados textuais.
print(l3) # Lista composta por por listas e dados mistos.

[1, 2, 3]
['Hello', 'World', '!']
[['Hello', 'World', '!'], [1, 2, 3]]


### <font color = lightblue>5.1.1.Objetos Iteráveis e Contagem de Elementos

Qualquer string usando a função *list()*, pode ser convertida em uma lista de sucessivos inteiros, e portanto, nesse sentido é um objeto iterável.
Pode se contar a quantidade de elementos de uma lista através de uma função já conhecida, a função *len()*.
Outra forma útil de criar listas numéricas é pela função *range( )*.

In [ ]:
l4 = "LISTADEELEMENTOS"
print(list(l4)) # Transformando string em lista.
print(len(l4)) # Contagem de elementos.
print(list(range(1,21,3))) # Criando uma sequência numérica de 0 até 21 na razão 3.

['L', 'I', 'S', 'T', 'A', 'D', 'E', 'E', 'L', 'E', 'M', 'E', 'N', 'T', 'O', 'S']
16
[1, 4, 7, 10, 13, 16, 19]


### <font color = lightblue>5.1.2.Operando Listas

Lembre de que uma lista em tese é interpretada como uma string, portanto sua operação trata-se de uma concatenação. Para somar os elementos deve-se usar a função *sum( )*.






In [ ]:
ls = l1 + l2
print(ls) # Somando listas* (concatenação).
print(l1*4) # Repetição.
print(str(sum(l1))) # Lembrando que para somar elementos* de uma lista deve ser apenas numeros.

[1, 2, 3, 'Hello', 'World', '!']
[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
6


### <font color = lightblue>5.1.3 Acessando Elementos de uma lista
Para acessar os elementos de uma lista usamos [ ], sinalizando elemento de interesse. lembrando que o primeiro índice começa em $0$.

In [ ]:
l4 = ['Hello', 'World', '!', 1, 2, 3]
print(l4[0])
print(l4[1])
print(l4[4])
print(l4[-1])
print(l4[-3])
print(l4[0:4])
print(l4[-1:3])
print(l4[0:])
print(l4[-4:])

Hello
World
2
3
1
['Hello', 'World', '!', 1]
[]
['Hello', 'World', '!', 1, 2, 3]
['!', 1, 2, 3]


Fatiamento: o python vê as strings como listas, e por tanto, é possível opera-las como tal, ditanto cada elemento de uma string como um elemento de uma lista. seja uma string armazenada em uma variável segue-se: *variável[x1: x2]*, para *x1* e *x2* posições iniciais e finais respectivamente.


In [ ]:
pi = "3.141595"
pi = pi[0:4]
pi1 = float(pi)
print(pi)
type(pi1)


3.14


float

Podemos acessar valores de uma lista como por exemplo: máximo, mínimo, indexação e elementos que se repete.

In [ ]:
print(max(l1)) # Valor máximo, função válida apenas para listas numéricas.
print(min(l1)) # Valor mínimo, função válida apenas para listas numéricas.
print(ls.index(3)) # Posição do elemento procurado na lista.
print(ls.count(1)) # Quantidade de repetição do elemento buscado.

3
1
2
1


### <font color = lightblue>5.1.5. Adicionando e Removendo Elementos de uma Lista

Pode-se adicionar e remover elementos de uma lista pelas funções *append( )*, *remove( )*, *pop( )*, *extend( )*, *del* e *clear( )*.

In [ ]:
print(l1)
l1.append(5) # Adicionando elemento.
print(l1)
l1.remove(1) # Removendo elemento discriminado.
print(l1)
l1.pop(2) # Removendo pela posição do elemento.
print(l1)
l1.extend([1]) # Adicionando um elemento, note que para adicionar um inteiro deve se criar uma lista, já que tal é uma string.
print(l1)
del l1[0] # Apagando um elemento pelo seu índice.
print(l1)
l1.clear() # Deletando todos os elemtentos da lista.
print(l1)

[1, 2, 3]
[1, 2, 3, 5]
[2, 3, 5]
[2, 3]
[2, 3, 1]
[3, 1]
[]


### <font color = lightblue>5.1.4. Organizando Listas

Listas podem ser organizadas pela função sort.



In [ ]:
print(l1) # Print antecipado.
print(l1.sort(reverse = True)) # Lista reversa.
print(l1) # Print antecipado.
print(l1.sort(reverse = False)) # Lista crescente.

[]
None
[]
None


### <font color = lightblue>5.1.6. Duplicando Listas
A duplicata de uma lista pode ser feita pela função *copy( )*.Caso simplismente atribuir uma variável para outra variável o valor armazenado será mutável, por isso a importância da função copy, pois armazena a mesma informação de uma variável para outra preservando a original, mesmo alterando a cópia.

In [ ]:
print(l1)
l5 = l1 # Alerando a cópia irá modificar a lista original.
print(l5)
l5[0] = ("Mutável")
print(l1)
print(l5)
l5 = l1.copy() # Fazendo uma cópia.
print(l1)
print(l5)
l5[0] = ("n + 1") # Alterando o valor da cópia e preservando o original.
print(l1)
print(l5)


[1, 2, 3]
[1, 2, 3]
['Mutável', 2, 3]
['Mutável', 2, 3]
['Mutável', 2, 3]
['Mutável', 2, 3]
['Mutável', 2, 3]
['n + 1', 2, 3]


## <font color = lightblue>5.2.Tuplas

In [ ]:
# Os valores de saída são inalteráveis.
Tup = (6, 7.1, "Text_2")
print(Tup)

(6, 7.1, 'Text_2')


## <font color = lightblue> 5.3.Dicionários

In [ ]:
# Os valores de saída sempre são strings.
# Os dicionários sāo construídos da seguinte forma:
# > Os valores são atribuidos como strings.
# > Separados por dois pontos (:).
# > Quebrados por vírgula(,).
dicionario = {
    "index" : "random",
    "id" : "var",
    "nome" : "Euler",
    "lista" : l1,
    "tupla" : Tup,
}
print(dicionario)

{'index': 'random', 'id': 'var', 'nome': 'Euler', 'lista': ['Mutável', 2, 3], 'tupla': (6, 7.1, 'Text_2')}


## <font color = lightblue> 5.4.Exercícios


<font color = yellow>  Exercício 1:

Criando um *script* com cinco valores de entrada determine o Desvio Médio Absoluto.

 Lembre que o Desvio Médio Absoluto é soma do módulo dos desvios em torno da média, e portanto, mede a variabilidade da amostra.  


 Nota* A equação do DM é dada por:

 $$D_m =\sum_{i=1}^{n}\frac{\vert x_i-\overline{x}\vert}{n}$$


In [ ]:
a = float(input("Digite o primeiro valor "))
b = float(input("Digite o segundo valor "))
c = float(input("Digite o terceiro valor "))
d = float(input("Digite o quarto valor "))
e = float(input("Digite o quinto valor "))

Valor_dm = [a, b, c, d, e]

Media_dm = sum(Valor_dm)/5

Vari_dm = []

for i in Valor_dm:
  n = abs(i - (Media_dm))
  Vari_dm.append(n)

DM = round((sum(Vari_dm)/5),2)

print("O desvio médio é: ", DM)


Digite o primeiro valor 3.14
Digite o segundo valor 2.7
Digite o terceiro valor 123.321
Digite o quarto valor 666.777
Digite o quinto valor 13 
O desvio médio é:  202.0


<font color = yellow>  Exercício 1:


Criando um script com cinco valores de entrada determine o Desvio Padrão Médio.
Lembre-se, o desvio padrão indica o quanto um conjunto de dados é uniforme. Quanto mais próximo de 0 for o desvio padrão, mais homogêneo são os dados.

Nota* A equação do DP para uma população é dada por:

$$\sigma = \sqrt{\frac{\sum_{i=1}^{n}(x_i-\mu)^2}{N}}$$

In [ ]:
import math

a = float(input("Digite o primeiro valor "))
b = float(input("Digite o segundo valor "))
c = float(input("Digite o terceiro valor "))
d = float(input("Digite o quarto valor "))
e = float(input("Digite o quinto valor "))

Valor_dm = [a, b, c, d, e]

Media_dp = sum(Valor_dm)/5

Vari_dp = []

for i in Valor_dm:
  n = ((i - (Media_dp))**2)/5
  Vari_dp.append(n)

DP = round(math.sqrt(sum(Vari_dp)),2)

print("O desvio padrão médio é: ", DP)

Digite o primeiro valor 1
Digite o segundo valor 2
Digite o terceiro valor 3
Digite o quarto valor 4
Digite o quinto valor 5
O desvio padrão médio é:  1.41


# <font color = lightblue> 6.Loops For e While

Loops são ferramentas de extrema utilidade para algoritmos que necessitam trabalhar de forma cíclica com suas variáveis. Há dois tipos de loops são eles: *For* e *While*, cada um com suas particularidades.

## <font color = lightblue>6.1.Loop For
 O loop **For** tem por objetivo iterar sobre strings, listas, tuplas e dicionários, com uma certa especificação para percorrer seu laço, sendo assim, precisa de uma condição pra interromper o laço para que não se perpetue.

In [ ]:
for Tabuada_5 in range(1, 11): # Especificação/condição para iterar no range (lista).
 print(Tabuada_5 * 5) # Operando sobre a sequência.

5
10
15
20
25
30
35
40
45
50


### <font color = lightblue>6.1.1 Loop For em Listas
Podemos usar um For dentro de uma lista para se criar uma outra lista desejada.

In [ ]:
# Criando a tabuada do 5 dentro de uma lista usando o For.
List_For = [ Tabuada_5 * 5 for Tabuada_5 in range(1, 11)]
# A variável e definida dentro da lista.
print(List_For)

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]


## <font color = lightblue>6.2.Loop While
O loop **While** tem por objetivo executar em laços uma tarefa até que atinga uma condição verdadeira para sua parada. Caso contrário, ele se reperirá infinitamente.

```
# Isto está formatado como código
```



In [ ]:
# Criando a tabuada do 5 usando o While.
Contador = 0 # Usando um contador para interar de 0 a 10.
while Contador <= 9:
  Contador = Contador + 1
  Tab5 = Contador * 5
  print(Tab5)


5
10
15
20
25
30
35
40
45
50


## <font color = lightblue>6.3.Estrutura Break e Continue

Muita das vezes será necessário parar um laço abruptamente, nesse caso, utilize a estrutura **break**. Caso seja necessário ignorar etapas no loop utiliza a estrutura **continue**.

In [ ]:
# Parando o código em uma detereminada etapa do laço.
for Tabuada_5 in range(1, 11):
  if Tabuada_5 == 5:
    break
  print(Tabuada_5 * 5)

5
10
15
20


In [ ]:
# Ignorando uma instrução dentro de um laço.
for Tabuada_5 in range(1, 11):
  if Tabuada_5 == 5:
     continue
     print("ignore")
  print(Tabuada_5 * 5)

5
10
15
20
30
35
40
45
50


# <font color = lightblue> 7.Importanto Pacotes
Para lidar com dados, muitas das ferramentas excedem os recursos básicos do Python, e portanto, a necessidade de irportar pacotes para suprir tal limitação.


## <font color = lightblue> 7.1.Import Datetime

Pacote responsável por criação e manipulação de datas. Usa-se *import* > *datetime*.

In [ ]:
# Importando o pacote de data.
import datetime
Hoje = datetime.date.today()

# Tipo de dado.
print(type(Hoje))

# Imprimindo o dia de hoje.
print(Hoje)

# Imprimindo a hora de hoje.
Hora = datetime.datetime.today().time()
print(Hora)

 # Criando uma data.
Data_hoje = datetime.date(2020, 12, 15)
Dia = Data_hoje.day
Mês = Data_hoje.month
Ano = Data_hoje.year
print(f"Hoje é dia  {Dia}, do mês {Mês}, de {Ano}")

# Intervalo de tempo.
Data_dif = Hoje - Data_hoje
print(Data_dif)

# Formatando data.
Data_form = Hoje.strftime("%d/%m/%y")
print(Data_form)

# Operação com datas.
print( f'Somando 60 dias, {Hoje + datetime.timedelta(days = 60)}' )
print( f'Diminuindo 60 dias, {Hoje - datetime.timedelta(days = 60)}' )

<class 'datetime.date'>
2023-12-15
14:08:06.181586
Hoje é dia  15, do mês 12, de 2020
1095 days, 0:00:00
15/12/23
Somando 60 dias, 2024-02-13
Diminuindo 60 dias, 2023-10-16


## <font color = lightblue> 7.2.Import Time
Pacote responsável por criação e manipulação de horas. Usa-se *import* > *time*.

In [ ]:
# Importando time.
import time

# Print temporizado.
print("Mensagem instântanea")
time.sleep(3)
print("Mensagem com retardo de 3 segundos")

# Hora atual.
Hora_ago = time.localtime()
print(Hora_ago)

# Tipo de dado.
print(type(Hora_ago))

# Formatando hora.
print( time.strftime('%m/%d/%Y, %H:%M:%S', Hora_ago ))

# Convertendo string para hora.
Hora_str = '23 March, 2021'
Hora_conv = time.strptime(Hora_str, '%d %B, %Y')
print(Hora_conv)
print( time.strftime('%m/%d/%Y, %H:%M:%S', Hora_conv ))

Mensagem instântanea
Mensagem com retardo de 3 segundos
time.struct_time(tm_year=2023, tm_mon=12, tm_mday=15, tm_hour=14, tm_min=45, tm_sec=8, tm_wday=4, tm_yday=349, tm_isdst=0)
<class 'time.struct_time'>
12/15/2023, 14:45:08
time.struct_time(tm_year=2021, tm_mon=3, tm_mday=23, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=1, tm_yday=82, tm_isdst=-1)
03/23/2021, 00:00:00


## <font color = lightblue> 7.3.Import Math

Muita das vezes é necessário artifícios matemáticos além dos já inclusos no próprio Python, como operadores aritiméticos e trigonométricos por exemplo.



**Funções Gerais**

In [ ]:
import math

# Valor abstoluto.
print(abs(-1))

# Arredondamento superior
print(math.ceil(math.pi))

# Arredondamento inferior
print(math.floor(math.pi))

# Distancia entre dois pontos
q = (1, 2)
w = (6, 4)

print(math.dist(q, w))


1
4
3
5.385164807134504


**Funções Trigonométricas**

In [ ]:
import math
# Função seno.
print(round(math.sin(math.pi/6),2))
# Função cosseno.
print(round(math.cos(math.pi/3),2))
# Função tangente.
print(round(math.tan(math.pi/4),2))

0.5
0.5
1.0


**Funções Exponenciais e Logaritmicas**


In [ ]:
import math
# Função logaritmo decimal.
print(math.log10(100))
# Função logaritmo geral.
print(math.log(36,6))
# Função logaritmo natural.
print(math.log(1,math.e))
# Função exponencial natural.
print(round(math.exp(1), 2))

2.0
2.0
0.0
2.72


## 7.4.Import Random
Pacote responsável por gerar valores aleatórios úteis para o estudo de probabilidades.

In [ ]:
import random
lista_r = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(random.choice(lista_r)) # Escolhendo ao acaso um valor dentro da lista_r.
palavra_r = "aleatorio"
print(random.choice(palavra_r)) # Escolhendo ao acaso uma letra dentro da variável.
print(round(random.random(), 2)) # Escolhendo um número aleatório entre 0 e 1.
print(random.randint(0,99)) # Escolhendo um intervalo para a escolha aleatória.

2
o
0.96
76


## 7.5.Import Statistics
Pacote responsável por importar as funções mais usuais em estatística.

In [ ]:
import statistics
lista_s = [0,1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584]
# Calculando a média aritmética simples.
print(round(statistics.mean(lista_s),2))
# Calculando a mediana
print(round(statistics.median(lista_s),2))
# Determinando a moda
print(statistics.mode(lista_s))

356
34
1
45


# <font color = lightblue> 8.Funções

Funções são blocos de scripts armazenados que são executados quado solicitados.



In [ ]:
# Criando uma função produto.
def Produto(fator_1, fator_2):
  Mult = fator_1 * fator_2
# Return retorna o valor bruto da função sem a necessidade de print.
  return Mult
# Testando a função
Produto(2, 3)

6

In [ ]:
# Solicitando a função:
import random

for loop in range (0, 9):

  p_1 = random.random()
  p_2 = random.random()

# Usando a função criada anteriormente.
  print(Produto(p_1, p_2))

0.5157310601132388
0.003986011548628758
0.08520994312007156
4.127249824677273e-05
0.09343812039701756
0.04342001653221746
0.3464705983943578
0.09420159559573253
0.3728970453702573


## <font color = lightblue> 8.1.Função Lambda
A função Lambda é uma função anônima, isto é, não precisa de definição nem retorno. Usamos o comando **lambda** para invoca-la, em seguida, o comando desejado em linha.

In [ ]:
# Função simples utilizando somente aritmética.
Soma_lambda = lambda vlr_1, vlr_2: vlr_1 + vlr_2
Soma_lambda(2,3)

5

In [ ]:
# Função de maior complexidade utilizando sentenças lógicas.
Tabuada = lambda num: [ Tabu * num for Tabu in range(1, 11)]
Tabuada(15)

[15, 30, 45, 60, 75, 90, 105, 120, 135, 150]

##<font color = lightblue> 8.2.Exercícios

<font color = yellow>  Exercício 1:

Crie uma função que calcule o discriminante de uma função quadrática. Dado por:

$$ \Delta = b^2 - 4ac $$

In [ ]:
def delta(a, b, c):
  delta = b**2 - 4 * a * c
  return delta

In [ ]:
delta (1, 2 , 2)

-4

<font color = yellow>  Exercício 2:

Crie uma função que calcule o $x_v$ e $y_v$ de uma função quadrática. Dados por:

$$ V(x_v, y_v) = \left( -\frac{b}{2a}, \frac{\Delta}{4a} \right) $$

In [ ]:
def Vertice(a, b, c):
  x_v = - b / 2 * a
  y_v = - delta(a, b, c) / 4 * a
  # print(" O x vértice é " + str(x_v) + " e o y vértice é " + str(y_v))
  return x_v, y_v

In [ ]:
Vertice (1, 2, 2)

(-1.0, 1.0)

<font color = yellow>  Exercício 3:

Crie uma função que calcule os zeros de uma função quadrática. Determinados por:

$$ x = \frac{{-b \pm \sqrt{{\Delta}}}}{{2a}} $$

In [ ]:
import math

def zeros_func(a, b, c):
  if a == 0:
    print("Não é função do segundo grau")
  if delta(a, b, c) < 0:
    print("A função não possui zeros reais")

  if delta(a, b, c) > 0:

    x_1 = (- b + math.sqrt(delta(a, b, c)))/ 2 * a
    x_2 = (- b - math.sqrt(delta(a, b, c)))/ 2 * a

    return x_1, x_2
    # print(" O x_1 é " + str(x_1) + " e o x_2 é " + str(x_2))

  if delta(a, b, c) == 0:
    x_0 = - b/ 2 * a
    print("Os zeros da função são iguais a: " + str(x_0))

In [ ]:
print(zeros_func(1, 4, 4))
print(zeros_func(1, 2, 2))
print(zeros_func(1, 5, 6))
print(zeros_func(0, 4, 4))

Os zeros da função são iguais a: -2.0
None
A função não possui zeros reais
None
(-2.0, -3.0)
Não é função do segundo grau
(0.0, -0.0)


# <font color = lightblue> 9.Tratamento de Erros
 Para o tratamento de erros usaremos a estrutura **Try**, **Except**, **Else** e **Finally** para encontrar os possíveis erros exceções classificando-os, para portanto contorna-los.

O try permite testar um script que apresente erros.

O except permite classificar o erro.

O else permite executar script quando não há erro.

O finally permite executar o script, independentemente do resultado dos blocos try e except.

In [ ]:
# Testando uma razão impossível.
try:
  0 / 0
except:
  print('Cálculo impossível')
finally:
  print('Execute isso de qualquer maneira')


Cálculo impossível
Execute isso de qualquer maneira


<font color = yellow>  Exercício 3:

Crie um script que armazene somente um número inteiro.


In [ ]:
def Leia_Int(Inteiro_msg):
  while True:
    try:
      Inteiro = int(input(Inteiro_msg))
    except(ValueError, TypeError):
      print('Argumento digitado não é um inteiro')
      continue
    except(KeyboardInterrupt):
      print('Usuário interrompeu a execução')
      return 0
    else:
      return Inteiro

n1 = Leia_Int("Digite um inteiro: ")
print('O inteiro digitado foi: ', n1)

Digite um inteiro: 3
3
O inteiro digitado foi:  3


# <font color = lightblue> 10.Arrays e  N-dimensional array

Arrays simples e multidimencionais são extremamente úteis quando estamos lidando com um único tipo de dado, especialmente se forem do tipo int ou float. A diferença entre arrays simples e N-dimensional arrays (arrays multidimensionais) em Python está principalmente na estrutura e na forma como os dados são organizados e acessados. Vamos explorar isso com mais detalhes adiante neste tópico.

## <font color = lightblue> 10.1.Arrays

Em Python, a estrutura de dados mais próxima do conceito de "array" em outras linguagens de programação são as listas. No entanto, Python também possui arrays, mas eles são menos comuns e têm algumas diferenças em comparação com listas.

**Listas**: As listas em Python como já visto antes são coleções ordenadas e mutáveis de elementos. Elas podem armazenar diferentes tipos de dados (números, strings, objetos, etc.).


**Arrays**: Arrays em Python são oferecidos pelo módulo array, que fornece uma estrutura de dados mais eficiente em termos de memória para armazenar grandes coleções de dados homogêneos (todos do mesmo tipo).

Devemos importar a bibliotéca array (*import > array*) ou numpy (*import > numpy*) para criar os arrays.

In [ ]:
import array
import numpy as np
# Criando um array de inteiros
meu_array = np.array([1, 2, 3, 4, 5])
print(meu_array)

[1 2 3 4 5]


### 10.1.1 <font color = lightblue>  Acessando Arrays

Podemos acessar elementos individuais de um array usando índices. Os índices começam em $0$.

In [ ]:
# Acessando o primeiro elemento
print(meu_array[0])

# Acessando o terceiro elemento
print(meu_array[2])

# Acessando o último elemento
print(meu_array[-1])

1
3
5


### 10.1.2 <font color = lightblue>  Códigos de Tipo em Arrays

Códigos de tipo são caracteres que especificam o tipo de elementos que um array do módulo array em Python pode armazenar. Eles garantem que todos os elementos do array sejam do mesmo tipo, o que é importante para a eficiência de memória e desempenho. Podemos listar três diretrizes.

**I - Eficiência de Memória**: Arrays utilizam uma quantidade fixa de memória por elemento, baseada no tipo de dado. Isso é mais eficiente do que listas, que podem armazenar elementos de diferentes tipos e têm mais overhead.

**II - Desempenho**: Operações em arrays são geralmente mais rápidas que em listas, pois o tipo de dado é conhecido e fixo.

**III - Interoperabilidade**: Facilita a integração com outras linguagens (como $C$) que esperam dados em formatos específicos.

<font color = lightblue> Código de tipo

Escolher o código de tipo depende do tipo de dados que você precisa armazenar no array. São eles:

**Inteiros Pequenos**: Use 'b' para inteiros com sinal de $1$ byte, ou 'B' para inteiros sem sinal de $1$ byte.


**Inteiros Médios**: Use 'h' ou 'H' para inteiros de $2$ bytes.


**Inteiros Grandes**: Use 'i', 'I', 'l', 'L', 'q', ou 'Q' dependendo do tamanho e se são com ou sem sinal.


**Números de Ponto Flutuante**: Use 'f' para floats (precisão simples) e 'd' para doubles (precisão dupla).


In [ ]:
# Criando um array de inteiros com o código de tipo 'i'
meu_array = array.array('i', [1, 2, 3, 4, 5])

# Acessando elementos
print(meu_array[0])

1


In [ ]:
# Criando um array de flutuantes com o código de tipo 'd'
meu_array = array.array('d', [1.1, 2.2, 3.3, 4.4, 5.5])

# Acessando elementos
print(meu_array[0])

1.1


## <font color = lightblue> 10.2.N-dimensional Arrays

ndarray (abreviação de N-dimensional array) é o principal objeto da biblioteca numpy. Ele representa um array multidimensional de elementos de um único tipo de dados. É altamente eficiente para operações matemáticas e científicas devido à sua implementação otimizada e à capacidade de operar sobre grandes volumes de dados de forma rápida e eficaz. Podemos listar três carcaterísticas importantes.

**I - Multidimensionalidade**: Pode ser um array de qualquer dimensão, desde $1D$ (vetor) até $nD$ (tensores).

**II - Homogeneidade**: Todos os elementos do ndarray são do mesmo tipo de dados.

**III - Operações Vetorizadas**: Suporta operações aritméticas e funções matemáticas aplicadas a todos os elementos de forma vetorizada, o que melhora significativamente o desempenho.






### <font color = lightblue> 10.2.1 Criação de ndarrays

Podemos criar um ndarray a partir de listas ou outras estruturas de dados usando a função **np.array()**.

In [2]:
import numpy as np

# Criando um array 1D
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)

[1 2 3 4 5]


In [ ]:
# Criando um array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [3]:
# Criando um array 3D
array_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array_3d, array_3d.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]] 3


<font color = lightblue> Outras formas de criar ndarrays


Criando arrays com zeros.


In [ ]:
# 1D
azeros = np.zeros(5)
azeros

array([0., 0., 0., 0., 0.])

In [ ]:
# 2D
bzeros = np.zeros((3, 4))
# 3 linhas e 4 colunas
bzeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 3D
czeros = np.zeros((3, 4, 2))
# 3 páginas, 4 linhas e 2 colunas
czeros

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

Criando ndarrays com uns.

In [ ]:
# 1D
aones = np.ones(5)
aones

array([1., 1., 1., 1., 1.])

In [ ]:
# 2D
bones = np.ones((3,4))
bones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# 3D
cones = np.ones((3,4,2))
cones

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

Criando ndarray com valores aleatórios

In [9]:
# Criando um ndarray variando de 1 a 100 randomizado, com 3 página, 4 linhas e 3 colunas.
nd_random = np.random.randint(1,101,(3,4,3))
nd_random

array([[[ 5, 25, 69],
        [70, 15, 53],
        [63, 60, 41],
        [90, 37, 49]],

       [[33, 77, 88],
        [95, 67, 55],
        [84, 13, 20],
        [76, 44,  1]],

       [[30, 77, 29],
        [72, 43, 53],
        [98, 23, 98],
        [92, 30, 26]]])

## <font color = lightblue>10.2.2 Acessando Ndarray
Podemos acessar elementos individuais de um ndarray usando índices. Os índices começam em $0$, assim como nos arrays.

In [11]:
# Acessando a primeira página.
print(nd_random[0])

# Acessando a primeira linha.
print(nd_random[0][0])

# Acessando o primeiro elemento da primeira página da primeira linha.
print(nd_random[0][0][0])

[[ 5 25 69]
 [70 15 53]
 [63 60 41]
 [90 37 49]]
[ 5 25 69]
5


<font color = lightblue> Acessando em condições e elementos específicos

In [24]:
# Acessando o primeiro elemento da segunda página da segunda linha.
print(nd_random[2][1][0])

# Acessando linhas dois a dois, da terceira página.
print(nd_random [2][:][::2])

# Acessando a terceira coluna da terceira página.
# Lista enumerada de linhas.
linha_random = [0,1,2,3]
# Lista enumerada de colunas.
coluna_random = [2,2,2,2]
# Acessando a coluna desejada.
print(nd_random[2][linha_random,coluna_random])

72
[[30 77 29]
 [98 23 98]]
[29 53 98 26]


# <font color = lightblue> 11.Orientação a Objetos

A linguagem Python é considerada uma linguagem multiparadigma, isto é, possibilita diferentes tipos de método de programação são elas: processual, funcional, imperativa e orientação a objetos.
A **orientação a obejtos** ou **OOP** de longe é o paradigma mais recorrente em Python, pois possibilita a interação entre objetos de forma mais eficaz. A OOP é sustentada em quatro pilares:

**I - Abstração**:Na programação orientada a objetos, a construção dos objetos é baseada em uma Classeque representa as características desse objeto.


**II - Encapsulamento**: O princípio de encapsulamento consiste em "esconder" a parte funcional dos objetos de forma que quem utiliza não tenha que conhecer mais do que o necessário para utilizá-lo.


**III - A herança**: Consiste em determinar que uma classe existe por si mesma, porém, ela é uma outra classe em sua essência.

**IV - Polimorfismo**: O conceito do polimorfismo é permitir que comportamentos comuns a $n$ tipos de classes possam ser definidos de forma específica para cada classe.



In [ ]:
class sujeito_bi:
  # Construindo um objeto (método construtor)
  def __init__(self, Nome, Ano):
    self.Nome = Nome
    self.Ano = int(Ano)

  def Ano_bissexto(self):
    print("Olá", self.Nome, "seu ano de nascimento é bissexto")
  def Ano_nbissexto(self):
    print("Olá", self.Nome, "seu ano de nascimento não é bissexto")

  def Calculo_idade(self):
    if self.Ano % 4 == 0:
      print("Excelente! =)")
      self.Ano_bissexto()
    else:
      print("Que pena! =(")
      self.Ano_nbissexto()


In [ ]:
Idade_bissexto = sujeito_bi("Saulo", 1994)
print(Idade_bissexto.Calculo_idade())
Idade_bissexto = sujeito_bi("Matheus", 1996)
print(Idade_bissexto.Calculo_idade())


Que pena! =(
Olá Saulo seu ano de nascimento não é bissexto
None
Excelente! =)
Olá Matheus seu ano de nascimento é bissexto
None


In [ ]:
dic = { "MG": {"Capital": "Belo Horizonte",
               "Cidades": {1:"Contagem",
                           2:"Luiz de Fora",
                           3:"Sete Lagoas"}
              },
        "SP": {"Capital": "São Paulo",
               "Cidades": {1:"Campinas",
                           2:"Piracicaba",
                           3:"Franca"}
              },
        "RS": {"Capital": "Porto Alegre",
               "Cidades": {1:"Pelotas",
                           2:"Gramado",
                           3:"Canela"}
              }
      }
dic["MG"]["Cidades"][2]= "Juiz de Fora"
dic


{'MG': {'Capital': 'Belo Horizonte',
  'Cidades': {1: 'Contagem', 2: 'Juiz de Fora', 3: 'Sete Lagoas'}},
 'SP': {'Capital': 'São Paulo',
  'Cidades': {1: 'Campinas', 2: 'Piracicaba', 3: 'Franca'}},
 'RS': {'Capital': 'Porto Alegre',
  'Cidades': {1: 'Pelotas', 2: 'Gramado', 3: 'Canela'}}}

In [ ]:
X = [3, 6, 1, 9, 2, 4, 7]
print(X[-1::-1])

print(X[6:0:-1])

print(X[:0:-1])

print(X[::-1])

print(X[6::-1])

[7, 4, 2, 9, 1, 6, 3]
[7, 4, 2, 9, 1, 6]
[7, 4, 2, 9, 1, 6]
[7, 4, 2, 9, 1, 6, 3]
[7, 4, 2, 9, 1, 6, 3]
